# Generated by Django 5.0.6 on 2024-09-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0008_report_date_report_name_alter_project_ortho_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordinates',
            field=models.CharField(blank=True, null=True),
        ),
    ]
