# Generated by Django 5.0.6 on 2024-10-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0011_surveyoutputimage_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.AddField(
            model_name='report',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Thermal_app.survey'),
        ),
    ]
