# Generated by Django 5.0.6 on 2024-10-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0015_rename_desription_taskdetails_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thermal_app.organization')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thermal_app.survey')),
            ],
        ),
    ]
