# Generated by Django 5.0.6 on 2024-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0016_surveyinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinvoice',
            name='name',
            field=models.CharField(default='invoice', max_length=100),
        ),
    ]
