# Generated by Django 5.0.6 on 2025-02-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Thermal_app", "0017_surveyinvoice_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="tile_link",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="defects_file",
            field=models.FileField(blank=True, upload_to="survey_defects_coordinates"),
        ),
        migrations.AlterField(
            model_name="surveyoutputimage",
            name="images",
            field=models.ImageField(
                blank=True, null=True, upload_to="survey_output_images"
            ),
        ),
        migrations.DeleteModel(
            name="ProjectPredictionImage",
        ),
    ]
