# Generated by Django 5.0.6 on 2024-08-23 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='Enter the location as: City, State', max_length=150)),
                ('power_capacity', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Power Capacity (in MW)')),
                ('type_of_survey', models.CharField(choices=[('EL', 'Electroluminescence'), ('TH', 'Thermal')], default='TH', max_length=2)),
                ('images', models.ImageField(help_text='Upload images in .jpeg, .png or .tiff format only', upload_to='images\\%Y%m')),
                ('report_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], null=True)),
                ('date', models.DateField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Thermal_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(help_text='Enter your number in the format: (country code) phone number', max_length=15)),
                ('organization', models.ForeignKey(db_column='organization_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='Thermal_app.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
