# Generated by Django 5.0.6 on 2024-09-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0006_rename_images_project_ortho_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ortho_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='ProjectPredictionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('geolocation', models.CharField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thermal_app.project')),
            ],
        ),
    ]
