# Generated by Django 5.0.6 on 2024-09-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0007_alter_project_ortho_image_projectpredictionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ortho_image',
            field=models.ImageField(blank=True, null=True, upload_to='orthomosaic images'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='thermal images'),
        ),
        migrations.AlterField(
            model_name='projectpredictionimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='predictions'),
        ),
    ]
