# Generated by Django 5.0.6 on 2024-10-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0009_project_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='power_capacity',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Power Capacity (in MW)'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('defects_file', models.FileField(blank=True, upload_to='survey_defects')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thermal_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyOutputImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='survey_output')),
                ('date', models.DateField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thermal_app.survey')),
            ],
        ),
    ]
