# Generated by Django 5.0.6 on 2024-10-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0010_alter_project_power_capacity_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyoutputimage',
            name='geolocation',
            field=models.CharField(blank=True, null=True),
        ),
    ]
