# Generated by Django 5.0.6 on 2024-10-19 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0013_remove_projectimage_project_projectimage_survey_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desription', models.CharField(max_length=300)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('progress', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Not Started')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('assignedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assignedto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Thermal_app.userprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thermal_app.taskcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thermal_app.organization')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thermal_app.survey')),
            ],
        ),
    ]
