# Generated by Django 5.0.6 on 2024-10-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thermal_app', '0014_taskcategory_taskdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdetails',
            old_name='desription',
            new_name='description',
        ),
    ]
